### PR TITLE
Added ts definition generator

### PR DESCRIPTION
**Pull request by corbane**
Hello, I added a script to generate a simple Ts definitions file.
https://github.com/neutralinojs/neutralino.js/issues/10#issuecomment-931407126

### CODE REVIEW

**Comment by shalithasuranga** [comment]
Hey.. @corbane Thank you very much for the contribution. I will check and merge this one soon!

**Review by shalithasuranga — APPROVED** [review]

**Comment by shalithasuranga** [comment]
Hey.. @corbane  Thanks! rollup looks good and now the minified file looks more lightweight too. Btw I changed the repo name here: https://github.com/neutralinojs/neutralino.js/commit/f7b2e5de9d847221f38ad6d2f8ed0a884728ec97 hope that's fine for you ;) I will check and update you about what we can do from the CLI side. maybe we can download it for TypeScript projects.

**Comment by shalithasuranga** [comment]
Is it okay if I add your Github profile link to https://neutralino.js.org/docs/community/committers ?

**Comment by corbane** [comment]
Hello @shalithasuranga 

Yes everything is good for me 👍 

juste:
```
I will check and update you about what we can do from the CLI side
```
I don't quite understand what this entails, (probably my poor English),
when you say 'CLI side' are you referring to the server side ?
if true, know that I am writing the definitions of the spec v2 in OpenApi / Swagger.

**Comment by shalithasuranga** [comment]
Ah, I meant from https://github.com/neutralinojs/neutralinojs-cli side. neu CLI is responsible for managing Neutralino projects. When we create a new project, CLI fetches the latest `neutralino.js` file from this repo. I was thinking about whether we can download `neutralino.d.ts` also. Then, if someone is making an app with Angular, they can update `typeRoot` to `<path>/neutralino.d.ts` to consume the definitions. Let me know if you need further info ;)

**Comment by corbane** [comment]
Oh yes okay !
thanks for the details, indeed, including the .d.ts in the starter project would be handy.

**Pull request merged**
